# Generated by Django 4.1.4 on 2023-01-18 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='guest',
            field=models.CharField(max_length=30),
        ),
    ]
