# Generated by Django 4.1.4 on 2023-01-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_alter_reservation_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='movie',
            field=models.CharField(max_length=30),
        ),
    ]
