# Generated by Django 4.1.4 on 2023-01-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0011_alter_reservation_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='movie_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
