# Generated by Django 4.1.4 on 2023-01-18 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0013_alter_reservation_movie_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reviewer',
            new_name='author',
        ),
    ]
